# Generated by Django 3.2.8 on 2021-10-06 10:32

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_apartament_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='apartament_content',
            field=wagtail.core.fields.StreamField([('Apartaments', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.RichTextBlock()), ('price', wagtail.core.blocks.CharBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False))]))], null=True),
        ),
    ]
