# Generated by Django 3.2.8 on 2021-10-06 12:13

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211006_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact',
            field=wagtail.core.fields.StreamField([('Contact', wagtail.core.blocks.StructBlock([('information', wagtail.core.blocks.RichTextBlock()), ('adress', wagtail.core.blocks.CharBlock()), ('phone', wagtail.core.blocks.CharBlock())]))], null=True),
        ),
    ]
