# Generated by Django 3.2.8 on 2021-10-06 12:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='carousel_content',
            field=wagtail.core.fields.StreamField([('Carousel', wagtail.core.blocks.StructBlock([('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('index', wagtail.core.blocks.CharBlock())]))], null=True),
        ),
    ]
