# Generated by Django 3.2.8 on 2021-10-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='background_image',
        ),
    ]
